In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 보스턴 주택값 데이터
from sklearn.datasets import load_boston

# 데이터 확인

In [2]:
boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
print(boston['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
# sklearn 에서 제공하는 함수는 보통 dictionary 형태로 가지고 있다.
boston.keys()
# data / target(정답) / feature_names(data name)

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

# train, test 로 분리

In [5]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [6]:
X = pd.DataFrame(boston.data,
                columns = boston.feature_names)
X

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [7]:
y = boston.target

- Lasso, Ridge 가 잘 적용이 되는지 확인하기 위해 일부러 과대적합(특성확장)을 만들어본다.

In [20]:
# 특성확장
extended_X = X.copy()
for col1 in X.columns: # 13번 반복
    for col2 in X.columns: # 13번 반복
        extended_X[col1+'x'+col2] = X[col1] * X[col2]

In [21]:
extended_X.shape

(506, 182)

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(extended_X, y, test_size=0.3, random_state = 3)

In [24]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((354, 182), (354,), (152, 182), (152,))

# LinearRegression

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
linear_model = LinearRegression()

In [27]:
linear_model.fit(X_train, y_train)

LinearRegression()

In [28]:
# train 에 맞춰져 있는 과대적합

print('train score: ', linear_model.score(X_train, y_train))
print('test score : ', linear_model.score(X_test, y_test))

train score:  0.9357787044789607
test score :  0.846041511351545


## Lasso 모델

In [29]:
from sklearn.linear_model import Lasso

In [30]:
# alpha : 0.01 ~ 100 사이 / 값 범위가 크다. (default = 1)
lasso_model = Lasso(alpha = 1)
lasso_model.fit(X_train, y_train)

C:\Users\SMHRD\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1864.6580473427884, tolerance: 3.075043446327684
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=1)

In [31]:
print('train score: ', lasso_model.score(X_train, y_train))
print('test score : ', lasso_model.score(X_test, y_test))

train score:  0.8924773076424393
test score :  0.7618500158284682


In [32]:
lasso_model.coef_

array([ 0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.18973585e-03,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -1.30850104e-03, -8.76586905e-03,
       -0.00000000e+00, -7.06389647e-03,  8.68442884e-05,  0.00000000e+00,
        2.90312900e-04, -5.41497703e-04,  0.00000000e+00,  3.26443745e-04,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  3.22546605e-02,
        1.14455217e-03, -0.00000000e+00, -0.00000000e+00, -5.01379896e-06,
        5.54195363e-04, -6.66165168e-04, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  1.57716296e-02, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -4.62868318e-03, -0.00000000e+00, -1.46445599e-02,
       -5.96084307e-04, -2.21335418e-02,  9.27139856e-04, -1.21193171e-03,
        0.00000000e+00,  

In [34]:
np.sum(lasso_model.coef_ == 0)

92

In [35]:
# np.sum() 함수
# True 의 개수를 세어줌

np.sum(lasso_model.coef_ != 0)

90

In [36]:
# False = 가중치 0
# True = 가중치가 0이 아님

lasso_model.coef_ == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False,  True,  True,  True, False, False,  True,  True, False,
       False, False,  True,  True,  True, False,  True,  True,  True,
       False,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True, False, False,  True, False,  True, False,  True,
       False, False, False,  True,  True,  True, False,  True, False,
       False, False,

In [37]:
lasso_model.coef_ != 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True,  True, False,  True,  True, False,  True,  True, False,
        True, False, False, False,  True,  True, False, False,  True,
        True,  True, False, False, False,  True, False, False, False,
        True, False,  True,  True,  True,  True,  True, False, False,
       False, False, False, False,  True, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False,  True,  True, False, False,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
        True,  True,  True, False, False, False,  True, False,  True,
        True,  True,

In [38]:
print('사용한 특성의 개수 : ', np.sum(lasso_model.coef_ != 0))

사용한 특성의 개수 :  90


In [41]:
# alpha 값을 낮춰주면 사용하는 특성의 개수가 늘어난다.

lasso_model = Lasso(alpha = 0.01)
lasso_model.fit(X_train, y_train)
print('train score: ', lasso_model.score(X_train, y_train))
print('test score : ', lasso_model.score(X_test, y_test))
print('사용한 특성의 개수 : ', np.sum(lasso_model.coef_ != 0))

train score:  0.9211874041774152
test score :  0.79609317025148
사용한 특성의 개수 :  161


C:\Users\SMHRD\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1277.6633556140712, tolerance: 3.075043446327684
  model = cd_fast.enet_coordinate_descent(


In [42]:
# alpha 값을 낮춰주면 사용하는 특성의 개수가 늘어난다.

lasso_model = Lasso(alpha = 0.001)
lasso_model.fit(X_train, y_train)
print('train score: ', lasso_model.score(X_train, y_train))
print('test score : ', lasso_model.score(X_test, y_test))
print('사용한 특성의 개수 : ', np.sum(lasso_model.coef_ != 0))

train score:  0.9251193330815224
test score :  0.8155877620813115
사용한 특성의 개수 :  176


C:\Users\SMHRD\Anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 1176.7848169700137, tolerance: 3.075043446327684
  model = cd_fast.enet_coordinate_descent(


## Ridgh 모델

- 일반적으로 Ridge 가 더 높은 예측 확률을 보여준다.

In [43]:
from sklearn.linear_model import Ridge

In [49]:
ridge_model = Ridge(alpha = 0.01)
ridge_model.fit(X_train, y_train)
print('train score: ', ridge_model.score(X_train, y_train))
print('test score : ', ridge_model.score(X_test, y_test))
print('사용한 특성의 개수 : ', np.sum(ridge_model.coef_ != 0))

train score:  0.9355408088384729
test score :  0.8414581014066758
사용한 특성의 개수 :  182


In [46]:
ridge_model = Ridge(alpha = 0.1)
ridge_model.fit(X_train, y_train)
print('train score: ', ridge_model.score(X_train, y_train))
print('test score : ', ridge_model.score(X_test, y_test))
print('사용한 특성의 개수 : ', np.sum(ridge_model.coef_ != 0))

train score:  0.9343723692555097
test score :  0.8253799428762403
사용한 특성의 개수 :  182


In [47]:
ridge_model = Ridge(alpha = 1)
ridge_model.fit(X_train, y_train)
print('train score: ', ridge_model.score(X_train, y_train))
print('test score : ', ridge_model.score(X_test, y_test))
print('사용한 특성의 개수 : ', np.sum(ridge_model.coef_ != 0))

train score:  0.9309167054043046
test score :  0.7989541028436475
사용한 특성의 개수 :  182
