In [3]:
import module_test

In [3]:
module_test.add(10,20)

30

# numpy 란.

In [4]:
import random as rd
import numpy as np

# 1차원 array 생성하기
1. 1차원 LIST데이터 생성
2. 생성된 데이터에 ARRAY 담아주기

In [11]:
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
arr1

array([1, 2, 3, 4, 5])

In [6]:
np.array([1,2,3,4,5]) # 직접 집어넣기도 가능하다

array([1, 2, 3, 4, 5])

# 2차원 array 생성하기
1. 2차원 LIST데이터 생성
2. 생성된 데이터에 ARRAY 담아주기

In [12]:
list2 = [[1,2,3], [4,5,6]]
arr2 = np.array(list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

# 배열의 크기 확인하기
- Shape 함수

In [13]:
print(arr1)
print()
print(arr2)

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]


In [14]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [ ]:
알트 유


# 배열의 전체 요소 개수 확인하기
- size

In [16]:
print(arr1.size)
print(arr2.size)

5
6


# 배열의 타입 확인하기
- dtype

In [20]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


- int32 : ~ 2^32
    

# 배열의 차원 확인하기
- ndim

In [23]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [7]:
list3 = [[1,2], [3,4], [5,6], [7,8]]
arr3 = np.array(list3)

### 3차원 배열의 다양한 정보 확인하기
- 배열의 크기
- 배열의 차원
- 배열의 개수

In [8]:
print(arr3.shape)
print(arr3.ndim)
print(arr3.size)

(4, 2)
2
8


In [9]:
print('배열의 크기 : ', arr3.shape)
print('배열의 차원 : ', arr3.ndim)
print('배열의 개수 : ', arr3.size)

배열의 크기 :  (4, 2)
배열의 차원 :  2
배열의 개수 :  8


### 특정한 값으로 배열 생성
- 0과 1로 구성된 배열 생성
-0으로 만들기
-np.zeros(배열의 크기)
-np.ones(배열의 크기(행,열))

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 원하는 값으로 배열 생성하기
- np.full()
-np.full((배열의 크기, 채울 값))

In [12]:
### (5,5)의 배열을 7로 채우기
np.full((5,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

### 1~50이 담긴 배열 생성하기
1. 1~50이 담긴 리스트 생성하기 (for문)
    - 비어있는 리스트 생성
    - 1~50까지 실행되는 for문 만들기
    - for문이 한 번씩 진행될 때 마다 리스트에 값 추가
2. 생성된 리스트를 배열에 담기

In [14]:
list = []

for i in range(1,51):
    list.append(i)
print(list, end = " ")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50] 

In [15]:
arr50 = np.array(list)
arr50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### 1~50 담긴 배열 생성하기
    - np.arrange(시작수, 끝수+1, step)

In [ ]:
# 1~50이 담긴 배열 생성
# 1~50까지 10씩 늘어나는 값으로 된 배열 생성

In [17]:
np.arange(1, 51, 10)

array([ 1, 11, 21, 31, 41])

In [ ]:
np.array(값, dtype)

### 타입 지정하여 생성하기
 - dtype()

In [29]:
np.array([1,2,2.3,3,4],dtype = 'int32')
np.array([1,2,3], dtype = 'float64')

array([1., 2., 3.])

- astype()

In [28]:
arr_type = np.array([1,2,3,4])
arr_type.dtype

dtype('int32')

In [31]:
arr_type = arr_type.astype('float64')
arr_type

array([1., 2., 3., 4.])

### 랜덤값 배열 생성하기
 - np.random.rand()
 - 0과 1사이의 숫자로 이루어짐

In [32]:
np.random.rand(2,3)

array([[0.66225573, 0.81324678, 0.5634965 ],
       [0.37308427, 0.86591363, 0.74551433]])

- 정수값으로 범위 지정
- np.random.randint(숫자의 범위, size=(배열의 크기))

In [34]:
np.random.randint(2,5,size=(3,4))

array([[3, 2, 2, 2],
       [4, 3, 2, 4],
       [2, 4, 2, 4]])

### array 연산

In [36]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,6,7])

In [37]:
list1 = [1,2,3]
list2 = [5,6,7]

In [40]:
list1 + list2 # 이어진 새로운 리스트를 만듦.

[1, 2, 3, 5, 6, 7]

In [43]:
arr1 + arr2 # 같은 위치에 있는 값들끼리 연산

array([ 6,  8, 10])

In [42]:
arr1 * arr2

array([ 5, 12, 21])

### Array 인덱싱

In [46]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr[0]

array([1, 2, 3])

In [48]:
arr[1]

array([4, 5, 6])

In [49]:
arr[0,1]

2

### txt 파일 받아오기
- np.loadtxt('파일명', 구분자)

In [51]:
data = np.loadtxt('height_weight.txt',delimiter = ',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

### 연습문제 - BMI 지수 구하기
- 10명에 대한 키와 몸무게 데이터를 통해 BMI지수를 구하시오.
- BMI지수 = 몸무게(kg)/키(m)*키(m)

In [83]:
BMI = data[1]/(data[0]*data[0])
BMI*10000 


array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [82]:
#쌤 풀이
height = data[0] / 100 # cm를 m로 바꿈.
weight = data[1]
bmi = weight / (height * height)
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

### 2차원 Array 생성
1. 1차원 array 생성
    - 1~50까지 값이 담긴 array
2. 차원 변경해주기

In [86]:
# arange() 사용해서 1부터 50까지 어레이 생성
arr2=np.arange(1,51)
arr2


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [88]:
# reshape(다시 만들 차원의 크기)로 차원을 다시 잡아준다.
# 총 요소의 개수가 원래 만들어져있는 것과 같아야 한다.
arr2 = arr2.reshape(5,10)
arr2

#1차원 어레이가 5,10의 2차원 어레이로 변경되었다.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

### Array 슬라이싱
- [큰 차원의 범위, 작은차원의 범위]
- :

In [93]:
# arr2[:2, :] #2행까지, 뒤 차원의 값은 전부다.
arr2[:2] # 뒤차원 생략해도 똑같음.

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [95]:
arr2[:3, :4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24]])

In [96]:
arr2[[2,3],[2,3]]

array([23, 34])

### Boolean 인덱싱
- True의 값을 가져옴

In [98]:
name = np.array(['태양', '명훈', '동원', '예호'])
name

array(['태양', '명훈', '동원', '예호'], dtype='<U2')

In [99]:
name[1]

'명훈'

In [100]:
bol = np.array([False, True, False, False])
bol

array([False,  True, False, False])

In [101]:
name[bol]

array(['명훈'], dtype='<U2')

In [102]:
name == '명훈'

array([False,  True, False, False])

In [170]:
name[name=='명훈'] # <-- name == 명훈 인 것만 출력해줌.

array(['명훈'], dtype='<U2')

In [105]:
name_score = np.array([[60,60],[70,70],[80,80],[90,90]])
name_score

array([[60, 60],
       [70, 70],
       [80, 80],
       [90, 90]])

In [106]:
name_score[name=='명훈']

array([[70, 70]])

In [107]:
print(name_score[name=='명훈'])
print(name_score[[False,True,False,False]])

[[70 70]]
[[70 70]]


### sum 함수

In [112]:
# 1~9 범위의 숫자가 담긴 랜덤한 (2,5) 배열 생성
#random.randint

import random
arr = np.random.randint(1,10, size = (2,5))
arr

array([[2, 7, 1, 1, 3],
       [4, 2, 2, 9, 2]])

In [113]:
np.sum(arr)

33

- axis(0) : 세로로 있는 값들이 더해짐
- axis(1) : 가로로 있는 값들이 더해짐

In [114]:
arr

array([[2, 7, 1, 1, 3],
       [4, 2, 2, 9, 2]])

In [115]:
np.sum(arr, axis = 0)

array([ 6,  9,  3, 10,  5])

In [116]:
np.sum(arr, axis = 1)

array([14, 19])

### mean 함수 - 평균
- axis

In [122]:
arr

array([[2, 7, 1, 1, 3],
       [4, 2, 2, 9, 2]])

In [121]:
np.mean(arr)

3.3

In [118]:
np.mean(arr, axis = 0)

array([3. , 4.5, 1.5, 5. , 2.5])

In [119]:
np.mean(arr, axis = 1)

array([2.8, 3.8])

### sqrt 함수
- 제곱근

In [124]:
arr

array([[2, 7, 1, 1, 3],
       [4, 2, 2, 9, 2]])

In [125]:
np.sqrt(arr)

array([[1.41421356, 2.64575131, 1.        , 1.        , 1.73205081],
       [2.        , 1.41421356, 1.41421356, 3.        , 1.41421356]])

### abs 함수
- 절대값(부호를 모두 제외)

In [128]:
arr = np.array([-1,2,-3,4,-5])
arr

array([-1,  2, -3,  4, -5])

In [129]:
np.abs(arr)

array([1, 2, 3, 4, 5])

## 데이터 분석하기
- 구분기호 :: 사용
- 데이터 타입 int

In [4]:
data = np.loadtxt('ratings.txt',delimiter = '::', dtype = 'int')

data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]])

In [160]:
data.shape

(1000209, 4)

In [2]:
import random as rd
import numpy as np

### 전체 평점 평균 구하기

In [161]:
data[:,2].mean() # 인덱스 2번이 평점이다.

3.581564453029317

### 1번 사용자의 평점 평균 구하기
1. 1번 사용자 Boolean 인덱싱 해오기
2. 인덱싱 해온 데이터의 평점 평균 구하기

In [5]:
#1단계
user_id1 = data[data[:,0] == 1]

In [6]:
#2단계
user_id1[:,2].mean()


4.188679245283019

### 각 사용자 별 평점 평균 구하기
- for 문 이용
- unique() : 데이터에서 중복을 제거하고 나열해주는 함수

In [7]:
user_id = np.unique(data[:,0]) # 1~6040번 까지 중복을 제거하고 하나씩만 출력해준다.
user_id
print(user_id.dtype)

int32


In [187]:
user_id.dtype

dtype('int32')

In [10]:
score = []

In [16]:
for i in user_id: # for문 한번 돌아갈 때 마다 i값을 가지고 있는 유저를 불러옴.
    user_id_score = data[data[:,0]==i][:,2].mean()
    score.append([i,user_id_score])
    
score_array = np.array(score).astype('float')
score_array

array([[1.00000000e+00, 4.18867925e+00],
       [2.00000000e+00, 3.71317829e+00],
       [3.00000000e+00, 3.90196078e+00],
       ...,
       [6.03800000e+03, 3.80000000e+00],
       [6.03900000e+03, 3.87804878e+00],
       [6.04000000e+03, 3.57771261e+00]])

In [20]:
# 쌤 풀이
for i in user_id:
    print(data[data[:,0]==i][:,2].mean()) # user id가 i인 유저들. ~6040번 까지
    

4.188679245283019
3.7131782945736433
3.9019607843137254
4.190476190476191
3.1464646464646466
3.9014084507042255
4.32258064516129
3.884892086330935
3.7358490566037736
4.114713216957606
3.2773722627737225
3.8260869565217392
3.388888888888889
3.32
3.3233830845771144
3.0285714285714285
4.075829383886256
3.6491803278688524
3.5725490196078433
4.083333333333333
2.909090909090909
3.0673400673400675
3.3157894736842106
3.948529411764706
3.7411764705882353
2.96
4.171428571428572
3.7570093457943927
3.5833333333333335
3.488372093023256
3.73109243697479
3.625
3.498721227621483
3.8658536585365852
3.54040404040404
4.199430199430199
3.69811320754717
3.58
3.564516129032258
3.4479166666666665
3.48
3.74025974025974
4.125
3.6321243523316062
2.946127946127946
4.219512195121951
3.909090909090909
3.068561872909699
3.712962962962963
3.0697674418604652
3.825
3.5569620253164556
4.2368421052631575
4.025
4.12
3.970149253731343
2.90625
3.9725400457665905
3.4741784037558685
3.414285714285714
2.7777777777777777
3.566

3.5
3.8793103448275863
3.6804123711340204
3.0
3.897810218978102
3.7222222222222223
3.7027027027027026
2.7023121387283235
4.0
3.44
2.6273408239700373
4.583333333333333
4.44
3.52
3.329113924050633
3.7054794520547945
3.05
3.9722222222222223
4.095238095238095
3.6564417177914113
3.6666666666666665
4.487341772151899
3.9642857142857144
3.8550724637681157
3.347826086956522
3.6666666666666665
4.282051282051282
4.040229885057471
4.2894736842105265
3.4662162162162162
4.485714285714286
3.0077922077922077
4.057395143487859
4.0
4.13855421686747
3.231404958677686
4.391304347826087
3.641509433962264
4.29559748427673
3.95
2.9523809523809526
4.473684210526316
3.3157894736842106
3.8518518518518516
3.652173913043478
3.1501340482573728
3.396103896103896
3.5238095238095237
3.0940766550522647
4.049180327868853
4.03030303030303
4.16
3.1882352941176473
4.346153846153846
3.484126984126984
3.9393939393939394
3.5
3.5849056603773586
3.8333333333333335
4.127659574468085
3.9545454545454546
4.086956521739131
3.0
3.90

3.6666666666666665
3.787341772151899
3.764625850340136
3.9550173010380623
3.2280701754385963
3.3666666666666667
3.7712082262210798
3.222413793103448
3.761904761904762
3.2213740458015265
3.216867469879518
4.145631067961165
3.849462365591398
4.796116504854369
4.343558282208589
3.386904761904762
4.42
3.813953488372093
3.267857142857143
3.74468085106383
3.662921348314607
3.9065934065934065
3.7566844919786098
3.3090128755364807
3.3726235741444865
4.30188679245283
3.772727272727273
3.3684210526315788
2.798941798941799
3.4654654654654653
3.7966101694915255
3.3146067415730336
2.5906298003072195
3.772727272727273
2.5704697986577183
2.736842105263158
3.375
3.1923076923076925
3.5833333333333335
4.2727272727272725
3.640625
2.56198347107438
3.074766355140187
3.968421052631579
3.551282051282051
3.640625
3.441048034934498
3.574468085106383
3.5
3.4285714285714284
3.4463519313304722
2.7711864406779663
4.011627906976744
4.321428571428571
3.5169300225733635
3.2493074792243766
3.125
4.208333333333333
4.14

3.3555555555555556
3.4391143911439115
2.9791666666666665
3.745011086474501
3.4923076923076923
2.264957264957265
3.8423076923076924
2.7760416666666665
2.9705882352941178
3.5849056603773586
3.780580075662043
2.8
3.988235294117647
4.205128205128205
3.658802177858439
2.472049689440994
2.6810344827586206
3.5
4.28755364806867
3.0625
4.061302681992337
3.064516129032258
3.2301587301587302
3.442953020134228
3.8421052631578947
3.647887323943662
3.2
3.3703703703703702
3.92
4.446808510638298
3.8
3.48
3.888888888888889
3.419597989949749
2.7719298245614037
3.967741935483871
3.891891891891892
3.64
4.130434782608695
3.4
3.6825396825396823
3.3425692695214106
3.4128256513026054
4.0
3.7333333333333334
4.714285714285714
3.8620689655172415
3.7435897435897436
4.37037037037037
3.727272727272727
3.208849557522124
3.492485549132948
3.558139534883721
3.4508196721311477
3.926829268292683
3.5556756756756758
4.132231404958677
4.407407407407407
3.4857142857142858
4.032258064516129
3.574418604651163
3.53571428571428

3.9215686274509802
3.811320754716981
3.6176470588235294
3.1842105263157894
3.652173913043478
3.8526912181303117
3.977777777777778
4.690140845070423
3.3968253968253967
3.4864864864864864
3.9292035398230087
4.470588235294118
3.95
3.5833333333333335
3.9395604395604398
4.104166666666667
3.6602972399150744
4.093333333333334
3.6901408450704225
2.463963963963964
3.9424657534246577
3.810810810810811
4.23015873015873
4.445544554455446
3.059866962305987
3.771043771043771
3.5842696629213484
4.136094674556213
4.217877094972067
3.6206896551724137
4.287356321839081
3.267123287671233
2.838630806845966
3.33224043715847
3.6666666666666665
3.6857142857142855
4.233333333333333
4.276450511945392
3.441780821917808
3.72992700729927
3.05679012345679
3.6
3.8923076923076922
3.1842105263157894
3.8264462809917354
4.0
2.869158878504673
3.4147286821705425
3.9722222222222223
4.107142857142857
3.6417910447761193
3.0697674418604652
3.1052631578947367
4.3538461538461535
3.2816901408450705
4.053803339517625
3.515151515

3.3
4.411764705882353
4.0
4.16
3.3877551020408165
3.219298245614035
2.4146341463414633
3.6847826086956523
4.041666666666667
4.090909090909091
4.08
3.5217391304347827
3.081081081081081
2.75
3.2
2.5
3.9411764705882355
2.72
3.55
3.3333333333333335
3.75
3.76
3.871794871794872
4.145299145299146
3.0526315789473686
3.823529411764706
3.4347826086956523
3.4285714285714284
3.8097560975609754
3.6285714285714286
4.595238095238095
3.352272727272727
3.3582089552238807
4.478260869565218
3.9808917197452227
4.271428571428571
4.111111111111111
4.434343434343434
3.87603305785124
3.4166666666666665
3.702970297029703
3.5463659147869673
4.438095238095238
3.40625
3.696551724137931
4.0
2.861111111111111
3.569476082004556
1.3043478260869565
3.8527918781725887
3.8771929824561404
4.302158273381295
2.708588957055215
3.9555555555555557
4.295
3.4269662921348316
3.2962962962962963
3.784158415841584
3.79
4.434782608695652
4.03765690376569
3.953488372093023
4.0
3.55
4.102941176470588
3.515527950310559
4.0
2.76
4.18644

3.6639344262295084
3.8214285714285716
3.77511961722488
4.1
3.242424242424242
3.4761904761904763
3.0689655172413794
4.053333333333334
3.869565217391304
2.6857142857142855
2.782742681047766
4.031578947368421
4.5
3.597560975609756
4.2926829268292686
3.419457735247209
4.285714285714286
4.583333333333333
3.576923076923077
3.84
2.6818181818181817
3.75
4.021299254526092
3.2888888888888888
4.11340206185567
3.824324324324324
4.375
3.238095238095238
4.4375
4.052980132450331
3.9640883977900554
3.696774193548387
3.4767441860465116
4.4
4.1647058823529415
4.278846153846154
4.666666666666667
3.6153846153846154
3.189265536723164
3.6457564575645756
4.121212121212121
2.7782608695652176
3.001503759398496
3.613107822410148
4.002994011976048
4.021978021978022
4.0
3.9727272727272727
4.242857142857143
3.4390243902439024
3.1270125223613596
4.0
4.270833333333333
3.8412698412698414
4.904761904761905
2.4615384615384617
3.9473684210526314
3.505586592178771
3.4835164835164836
3.5072463768115942
3.8333333333333335


3.359154929577465
4.290243902439024
4.003759398496241
2.6844349680170576
3.8541666666666665
3.4265927977839334
4.0
3.806451612903226
3.9047619047619047
3.6293103448275863
2.6886291179596173
3.625
4.24
4.483870967741935
4.061538461538461
3.875
3.7804878048780486
3.2
4.031746031746032
4.05
3.75
4.231788079470198
4.264
3.388888888888889
3.5761266747868454
2.789473684210526
3.0681818181818183
4.137931034482759
4.014851485148514
3.4814814814814814
3.6333333333333333
3.9921875
3.492957746478873
3.8142857142857145
3.1818181818181817
3.6363636363636362
3.5614973262032086
3.7837837837837838
2.9580838323353293
3.3410041841004183
2.9844559585492227
4.404255319148936
4.402985074626866
3.8
3.526315789473684
4.447761194029851
3.5
4.333333333333333
3.9371069182389937
3.452830188679245
4.1063829787234045
4.0423728813559325
4.4222222222222225
2.916323731138546
3.4239130434782608
3.9510268562401265
3.004911591355599
2.9674134419551934
3.857142857142857
3.747311827956989
3.9285714285714284
3.008515815085

3.246376811594203
3.3783783783783785
3.264516129032258
3.7709251101321586
3.4583333333333335
2.994296577946768
3.4601769911504423
4.666666666666667
2.8823529411764706
3.806451612903226
3.7804878048780486
4.134825014343087
3.9166666666666665
3.373469387755102
3.534090909090909
3.588235294117647
3.586206896551724
3.7868852459016393
2.7435897435897436
3.753875968992248
3.645
3.744027303754266
4.111111111111111
3.8701298701298703
4.052631578947368
3.5450236966824646
3.2291666666666665
4.357142857142857
3.1847133757961785
2.225
3.693548387096774
4.276595744680851
4.252631578947368
4.1
3.325
4.170731707317073
3.8821138211382116
3.6737967914438503
4.2
3.7244897959183674
3.6483516483516483
3.7058823529411766
3.2403846153846154
3.8181818181818183
3.8754208754208754
2.9468085106382977
3.278595696489241
4.083333333333333
3.787878787878788
3.8774193548387097
3.4871794871794872
3.5686274509803924
3.847916666666667
3.8627450980392157
4.2592592592592595
3.9649122807017543
3.437974683544304
3.57664233

3.641304347826087
4.0
4.068965517241379
3.9655172413793105
3.9411764705882355
3.5
4.013888888888889
3.8518518518518516
3.9936305732484074
4.0
3.6666666666666665
3.7613168724279835
4.105263157894737
3.798780487804878
3.0228310502283104
3.7468354430379747
3.262295081967213
4.04424778761062
4.232558139534884
3.8958333333333335
3.8426395939086295
3.478723404255319
3.5806451612903225
4.181818181818182
3.3821138211382116
4.026666666666666
3.8215434083601285
3.7094972067039107
3.3263157894736843
3.689655172413793
4.0
3.5365853658536586
4.214285714285714
4.387096774193548
3.93
4.055555555555555
3.7157894736842105
3.604651162790698
3.45610278372591
3.761904761904762
3.9545454545454546
4.029556650246305
2.84
3.884020618556701
4.466666666666667
3.9901960784313726
3.392857142857143
4.344481605351171
4.347328244274809
3.4210526315789473
3.7857142857142856
3.175
3.933333333333333
3.902439024390244
4.132352941176471
3.073170731707317
3.35
4.167364016736402
3.6653061224489796
4.086956521739131
3.81675

3.863013698630137
3.4347826086956523
4.136363636363637
3.1857142857142855
3.3616018845700824
3.6942148760330578
4.1234567901234565
3.2989690721649483
4.035714285714286
4.016666666666667
3.6666666666666665
4.089041095890411
3.5760869565217392
3.5
3.8476190476190477
3.603448275862069
3.3524590163934427
4.222222222222222
4.0588235294117645
3.238095238095238
3.5217391304347827
2.8333333333333335
3.8597122302158273
4.181818181818182
3.7721518987341773
3.5090909090909093
4.208333333333333
3.2
3.632
3.752808988764045
2.657142857142857
3.8875
3.737142857142857
4.040816326530612
3.8074074074074074
3.8043478260869565
3.435810810810811
4.580246913580247
3.979381443298969
3.8671875
3.835714285714286
3.9545454545454546
3.9672131147540983
2.990344827586207
4.008196721311475
4.195652173913044
3.5757575757575757
3.6538461538461537
3.4725274725274726
3.590909090909091
4.314285714285714
3.795918367346939
3.984375
4.132832080200501
2.9743589743589745
3.8187919463087248
4.444444444444445
4.320610687022901

3.061688311688312
4.48
3.5294117647058822
3.77959927140255
3.289473684210526
3.292307692307692
3.772727272727273
4.363636363636363
3.5164835164835164
3.8444444444444446
3.558282208588957
3.711670480549199
4.388888888888889
3.4334763948497855
3.9074074074074074
3.4047619047619047
4.098039215686274
3.1979949874686717
3.727272727272727
3.6320754716981134
3.617857142857143
3.9291338582677167
4.107142857142857
4.7
3.727272727272727
4.441666666666666
3.389830508474576
3.2278481012658227
3.9740259740259742
3.444055944055944
3.588235294117647
3.4776119402985075
3.566666666666667
4.32051282051282
3.956989247311828
3.8104906937394247
4.4035087719298245
3.2721518987341773
4.111111111111111
3.2450592885375493
3.594017094017094
4.071641791044776
4.106299212598425
3.3859649122807016
3.6704545454545454
3.161290322580645
3.1533742331288344
3.5714285714285716
3.34375
3.971608832807571
3.969543147208122
3.0
4.080645161290323
3.8867924528301887
3.754385964912281
3.189218921892189
3.515151515151515
3.5911

In [18]:
data[data[:,0]==1][:,2].mean()  #1번 사용자의 평점의 평균

4.188679245283019